import { useState, useEffect, useCallback } from 'react';
import { X, Info, FileSpreadsheet } from 'lucide-react';
import { API_ENDPOINTS } from '../config';
import './HeaderPreviewModal.css';

const TYPE_OPTIONS = [
  { label: 'text',    dtype: 'object' },
  { label: 'integer', dtype: 'Int64' },
  { label: 'decimal', dtype: 'float64' },
  { label: 'boolean', dtype: 'bool' },
  { label: 'date',    dtype: 'datetime64[ns]' },
];

function pandasDtypeToDropdownValue(rawDtype) {
  const d = rawDtype.toLowerCase();
  if (d === 'object' || d === 'string')          return 'object';
  if (d.startsWith('int'))                       return 'Int64';
  if (d.startsWith('float') || d === 'double')   return 'float64';
  if (d === 'bool' || d === 'boolean')            return 'bool';
  if (d.startsWith('datetime'))                   return 'datetime64[ns]';
  return 'object'; // fallback
}

export default function HeaderPreviewModal({
  open,
  onConfirm,
  onCancel,
  tempFilePath,
  hasHeader,
  headersAutoGenerated,
  sessionToken,
}) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [columns, setColumns] = useState([]);
  const [columnsInfo, setColumnsInfo] = useState([]);
  const [dataRows, setDataRows] = useState([]);
  const [totalRows, setTotalRows] = useState(0);
  const [editedHeaders, setEditedHeaders] = useState([]);
  const [editedTypes, setEditedTypes] = useState([]);
  const [confirming, setConfirming] = useState(false);

  const fetchPreview = useCallback(async () => {
    if (!tempFilePath || !sessionToken) return;

    setLoading(true);
    setError(null);

    try {
      const formData = new FormData();
      formData.append('temp_file_path', tempFilePath);
      formData.append('limit', '10');
      formData.append('has_header', String(hasHeader));

      const response = await fetch(API_ENDPOINTS.DATASETS.PREVIEW_TEMP, {
        method: 'POST',
        headers: { 'Authorization': `Bearer ${sessionToken}` },
        body: formData,
      });

      if (!response.ok) {
        const err = await response.json();
        throw new Error(err.detail || 'Failed to fetch preview');
      }

      const data = await response.json();
      setColumns(data.columns || []);
      setColumnsInfo(data.columns_info || []);
      setDataRows(data.data || []);
      setTotalRows(data.row_count || 0);
      setEditedHeaders(data.columns || []);
      setEditedTypes(
        (data.columns_info || []).map(ci => pandasDtypeToDropdownValue(ci.type))
      );
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }, [tempFilePath, hasHeader, sessionToken]);

  useEffect(() => {
    if (open) {
      fetchPreview();
    }
  }, [open, fetchPreview]);

  const handleHeaderChange = (index, value) => {
    setEditedHeaders(prev => {
      const next = [...prev];
      next[index] = value;
      return next;
    });
  };

  const handleTypeChange = (index, value) => {
    setEditedTypes(prev => {
      const next = [...prev];
      next[index] = value;
      return next;
    });
  };

  const handleConfirm = async () => {
    setConfirming(true);
    setError(null);

    try {
      // Build column_types dict: {col_name: dtype}
      const columnTypes = {};
      editedHeaders.forEach((header, i) => {
        if (editedTypes[i]) columnTypes[header] = editedTypes[i];
      });

      // Always call confirm-headers to sanitize
      const formData = new FormData();
      formData.append('temp_file_path', tempFilePath);
      formData.append('headers', JSON.stringify(editedHeaders));
      formData.append('has_header', String(hasHeader));
      formData.append('column_types', JSON.stringify(columnTypes));

      const response = await fetch(API_ENDPOINTS.DATASETS.CONFIRM_HEADERS, {
        method: 'POST',
        headers: { 'Authorization': `Bearer ${sessionToken}` },
        body: formData,
      });

      if (!response.ok) {
        const err = await response.json();
        throw new Error(err.detail || 'Failed to confirm headers');
      }

      onConfirm();
    } catch (err) {
      setError(err.message);
    } finally {
      setConfirming(false);
    }
  };

  if (!open) return null;

  const displayRows = dataRows.slice(0, 10);

  return (
    <div className="header-preview-overlay" onClick={onCancel}>
      <div className="header-preview-modal" onClick={e => e.stopPropagation()}>
        {/* Header */}
        <div className="header-preview-header">
          <h2>
            <FileSpreadsheet size={20} />
            Preview Dataset
          </h2>
          <button className="header-preview-close" onClick={onCancel}>
            <X size={20} />
          </button>
        </div>

        {/* Info banner for auto-generated headers */}
        {headersAutoGenerated && (
          <div className="header-preview-info">
            <Info size={16} />
            <span>
              No header row detected. Default column names have been assigned. You can edit them below.
            </span>
          </div>
        )}

        {/* Body */}
        <div className="header-preview-body">
          {loading ? (
            <div className="header-preview-loading">
              <div className="spinner" />
              <span>Loading preview...</span>
            </div>
          ) : error && dataRows.length === 0 ? (
            <div className="header-preview-error">{error}</div>
          ) : (
            <div className="header-preview-table-wrapper">
              <table className="header-preview-table">
                <thead>
                  <tr>
                    <th className="row-num">#</th>
                    {editedHeaders.map((header, i) => (
                      <th key={i}>
                        {headersAutoGenerated ? (
                          <input
                            className="header-input"
                            value={header}
                            onChange={e => handleHeaderChange(i, e.target.value)}
                            spellCheck={false}
                          />
                        ) : (
                          header
                        )}
                      </th>
                    ))}
                  </tr>
                  {/* Type row */}
                  <tr className="type-row">
                    <td className="row-num"></td>
                    {columnsInfo.map((col, i) => (
                      <td key={i}>
                        <select
                          className="type-select"
                          value={editedTypes[i] || 'object'}
                          onChange={e => handleTypeChange(i, e.target.value)}
                        >
                          {TYPE_OPTIONS.map(opt => (
                            <option key={opt.dtype} value={opt.dtype}>
                              {opt.label}
                            </option>
                          ))}
                        </select>
                      </td>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {displayRows.map((row, rowIdx) => (
                    <tr key={rowIdx}>
                      <td className="row-num">{rowIdx + 1}</td>
                      {row.map((cell, cellIdx) => (
                        <td key={cellIdx}>
                          {cell === null || cell === undefined ? (
                            <span style={{ color: 'var(--text-muted)', fontStyle: 'italic' }}>null</span>
                          ) : (
                            String(cell)
                          )}
                        </td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="header-preview-footer">
          <span className="row-count-info">
            Showing {displayRows.length} of {totalRows.toLocaleString()} rows
          </span>

          {error && dataRows.length > 0 && (
            <span style={{ color: 'var(--accent-red)', fontSize: '0.82rem' }}>{error}</span>
          )}

          <div className="header-preview-actions">
            <button
              className="header-preview-btn secondary"
              onClick={onCancel}
              disabled={confirming}
            >
              Cancel
            </button>
            <button
              className="header-preview-btn primary"
              onClick={handleConfirm}
              disabled={loading || confirming}
            >
              {confirming ? 'Confirming...' : 'Confirm'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
